# Generated by Django 3.2.5 on 2022-02-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=100, verbose_name='Start Point')),
                ('check_point_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Check point 1')),
                ('check_point_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Check point 2')),
                ('check_point_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Check point 3')),
                ('end_point', models.CharField(max_length=100, verbose_name='End Point')),
            ],
        ),
    ]
